/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Point = {
  x: number;
  y: number;
};

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Checkpoint {
  abbreviation: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  name: string;
  point: Point;
  trackId: number;
  updatedAt: Generated<Timestamp>;
}

export interface Event {
  createdAt: Generated<Timestamp>;
  description: string | null;
  endDate: Timestamp;
  id: Generated<number>;
  isActive: Generated<boolean>;
  name: string;
  slug: string;
  startDate: Timestamp;
  updatedAt: Generated<Timestamp>;
}

export interface Track {
  color: Generated<string>;
  createdAt: Generated<Timestamp>;
  endPoint: Point;
  eventId: number;
  id: Generated<number>;
  isActive: Generated<boolean>;
  name: string;
  path: string;
  slug: string;
  startingPoint: Point;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  checkpoint: Checkpoint;
  event: Event;
  track: Track;
}
